// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.15.5
// source: user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqSignup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqSignup) Reset() {
	*x = ReqSignup{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqSignup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSignup) ProtoMessage() {}

func (x *ReqSignup) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSignup.ProtoReflect.Descriptor instead.
func (*ReqSignup) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *ReqSignup) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ReqSignup) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RespSignup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespSignup) Reset() {
	*x = RespSignup{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespSignup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespSignup) ProtoMessage() {}

func (x *RespSignup) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespSignup.ProtoReflect.Descriptor instead.
func (*RespSignup) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *RespSignup) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RespSignup) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReqSignin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqSignin) Reset() {
	*x = ReqSignin{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqSignin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSignin) ProtoMessage() {}

func (x *ReqSignin) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSignin.ProtoReflect.Descriptor instead.
func (*ReqSignin) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *ReqSignin) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ReqSignin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RespSignin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespSignin) Reset() {
	*x = RespSignin{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespSignin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespSignin) ProtoMessage() {}

func (x *RespSignin) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespSignin.ProtoReflect.Descriptor instead.
func (*RespSignin) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *RespSignin) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RespSignin) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RespSignin) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReqUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqUserInfo) Reset() {
	*x = ReqUserInfo{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUserInfo) ProtoMessage() {}

func (x *ReqUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUserInfo.ProtoReflect.Descriptor instead.
func (*ReqUserInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *ReqUserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type RespUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	SignupAt      string                 `protobuf:"bytes,6,opt,name=signupAt,proto3" json:"signupAt,omitempty"`
	LastActiveAt  string                 `protobuf:"bytes,7,opt,name=lastActiveAt,proto3" json:"lastActiveAt,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespUserInfo) Reset() {
	*x = RespUserInfo{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespUserInfo) ProtoMessage() {}

func (x *RespUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespUserInfo.ProtoReflect.Descriptor instead.
func (*RespUserInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *RespUserInfo) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RespUserInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RespUserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RespUserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RespUserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RespUserInfo) GetSignupAt() string {
	if x != nil {
		return x.SignupAt
	}
	return ""
}

func (x *RespUserInfo) GetLastActiveAt() string {
	if x != nil {
		return x.LastActiveAt
	}
	return ""
}

func (x *RespUserInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ReqUserFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqUserFile) Reset() {
	*x = ReqUserFile{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqUserFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUserFile) ProtoMessage() {}

func (x *ReqUserFile) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUserFile.ProtoReflect.Descriptor instead.
func (*ReqUserFile) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *ReqUserFile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ReqUserFile) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RespUserFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FileData      []byte                 `protobuf:"bytes,3,opt,name=fileData,proto3" json:"fileData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespUserFile) Reset() {
	*x = RespUserFile{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespUserFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespUserFile) ProtoMessage() {}

func (x *RespUserFile) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespUserFile.ProtoReflect.Descriptor instead.
func (*RespUserFile) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *RespUserFile) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RespUserFile) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RespUserFile) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type ReqUserFileRename struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Filehash      string                 `protobuf:"bytes,2,opt,name=filehash,proto3" json:"filehash,omitempty"`
	NewFileName   string                 `protobuf:"bytes,3,opt,name=newFileName,proto3" json:"newFileName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqUserFileRename) Reset() {
	*x = ReqUserFileRename{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqUserFileRename) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUserFileRename) ProtoMessage() {}

func (x *ReqUserFileRename) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUserFileRename.ProtoReflect.Descriptor instead.
func (*ReqUserFileRename) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *ReqUserFileRename) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ReqUserFileRename) GetFilehash() string {
	if x != nil {
		return x.Filehash
	}
	return ""
}

func (x *ReqUserFileRename) GetNewFileName() string {
	if x != nil {
		return x.NewFileName
	}
	return ""
}

type RespUserFileRename struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FileData      []byte                 `protobuf:"bytes,3,opt,name=fileData,proto3" json:"fileData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespUserFileRename) Reset() {
	*x = RespUserFileRename{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespUserFileRename) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespUserFileRename) ProtoMessage() {}

func (x *RespUserFileRename) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespUserFileRename.ProtoReflect.Descriptor instead.
func (*RespUserFileRename) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *RespUserFileRename) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RespUserFileRename) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RespUserFileRename) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x15go.micro.service.user\"C\n" +
	"\tReqSignup\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\":\n" +
	"\n" +
	"RespSignup\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"C\n" +
	"\tReqSignin\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"P\n" +
	"\n" +
	"RespSignin\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\")\n" +
	"\vReqUserInfo\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\xdc\x01\n" +
	"\fRespUserInfo\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x1a\n" +
	"\bsignupAt\x18\x06 \x01(\tR\bsignupAt\x12\"\n" +
	"\flastActiveAt\x18\a \x01(\tR\flastActiveAt\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\"?\n" +
	"\vReqUserFile\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"X\n" +
	"\fRespUserFile\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bfileData\x18\x03 \x01(\fR\bfileData\"m\n" +
	"\x11ReqUserFileRename\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bfilehash\x18\x02 \x01(\tR\bfilehash\x12 \n" +
	"\vnewFileName\x18\x03 \x01(\tR\vnewFileName\"^\n" +
	"\x12RespUserFileRename\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bfileData\x18\x03 \x01(\fR\bfileData2\xc7\x03\n" +
	"\vUserService\x12O\n" +
	"\x06Signup\x12 .go.micro.service.user.ReqSignup\x1a!.go.micro.service.user.RespSignup\"\x00\x12O\n" +
	"\x06Signin\x12 .go.micro.service.user.ReqSignin\x1a!.go.micro.service.user.RespSignin\"\x00\x12U\n" +
	"\bUserInfo\x12\".go.micro.service.user.ReqUserInfo\x1a#.go.micro.service.user.RespUserInfo\"\x00\x12V\n" +
	"\tUserFiles\x12\".go.micro.service.user.ReqUserFile\x1a#.go.micro.service.user.RespUserFile\"\x00\x12g\n" +
	"\x0eUserFileRename\x12(.go.micro.service.user.ReqUserFileRename\x1a).go.micro.service.user.RespUserFileRename\"\x00B\aZ\x05/userb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_user_proto_goTypes = []any{
	(*ReqSignup)(nil),          // 0: go.micro.service.user.ReqSignup
	(*RespSignup)(nil),         // 1: go.micro.service.user.RespSignup
	(*ReqSignin)(nil),          // 2: go.micro.service.user.ReqSignin
	(*RespSignin)(nil),         // 3: go.micro.service.user.RespSignin
	(*ReqUserInfo)(nil),        // 4: go.micro.service.user.ReqUserInfo
	(*RespUserInfo)(nil),       // 5: go.micro.service.user.RespUserInfo
	(*ReqUserFile)(nil),        // 6: go.micro.service.user.ReqUserFile
	(*RespUserFile)(nil),       // 7: go.micro.service.user.RespUserFile
	(*ReqUserFileRename)(nil),  // 8: go.micro.service.user.ReqUserFileRename
	(*RespUserFileRename)(nil), // 9: go.micro.service.user.RespUserFileRename
}
var file_user_proto_depIdxs = []int32{
	0, // 0: go.micro.service.user.UserService.Signup:input_type -> go.micro.service.user.ReqSignup
	2, // 1: go.micro.service.user.UserService.Signin:input_type -> go.micro.service.user.ReqSignin
	4, // 2: go.micro.service.user.UserService.UserInfo:input_type -> go.micro.service.user.ReqUserInfo
	6, // 3: go.micro.service.user.UserService.UserFiles:input_type -> go.micro.service.user.ReqUserFile
	8, // 4: go.micro.service.user.UserService.UserFileRename:input_type -> go.micro.service.user.ReqUserFileRename
	1, // 5: go.micro.service.user.UserService.Signup:output_type -> go.micro.service.user.RespSignup
	3, // 6: go.micro.service.user.UserService.Signin:output_type -> go.micro.service.user.RespSignin
	5, // 7: go.micro.service.user.UserService.UserInfo:output_type -> go.micro.service.user.RespUserInfo
	7, // 8: go.micro.service.user.UserService.UserFiles:output_type -> go.micro.service.user.RespUserFile
	9, // 9: go.micro.service.user.UserService.UserFileRename:output_type -> go.micro.service.user.RespUserFileRename
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
